# Generated by Django 3.2 on 2022-12-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos/movies_thumb/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('default_rate', models.FloatField()),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('time', models.TimeField()),
                ('actors', models.CharField(max_length=150)),
                ('related', models.TextField(blank=True)),
                ('trailer', models.TextField(blank=True)),
                ('serial', models.BooleanField(default=False)),
            ],
        ),
    ]
