# Generated by Django 3.2 on 2022-12-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='movies',
            name='default_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='movies',
            name='time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
