# Generated by Django 3.2 on 2022-12-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221219_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='default_rate',
            field=models.FloatField(),
        ),
    ]
