# Generated by Django 3.2 on 2022-12-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_default_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='default_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
