# Generated by Django 3.2 on 2022-12-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20221219_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.CharField(blank=True, max_length=150, verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.CharField(blank=True, max_length=150, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='default_rate',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Рейтинг по умолчанию'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(blank=True, max_length=150, verbose_name='Режисер'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/movies_thumb/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='related',
            field=models.TextField(blank=True, verbose_name='Похожие'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='serial',
            field=models.BooleanField(default=False, verbose_name='Сериал'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailer',
            field=models.TextField(blank=True, verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Год'),
        ),
    ]
