# Generated by Django 3.2 on 2022-12-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20221220_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.category'),
        ),
    ]
