# Generated by Django 3.2 on 2022-12-20 10:23

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movies_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['title'],
            },
            bases=(movies.models.CustomStr, models.Model),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='movies',
            name='tags',
            field=models.ManyToManyField(blank=True, to='movies.Tags', verbose_name='Категория'),
        ),
    ]
