# Generated by Django 3.2 on 2022-12-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20221220_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='tags',
            field=models.ManyToManyField(blank=True, to='movies.Tags', verbose_name='Теги'),
        ),
    ]
