# Generated by Django 3.2 on 2022-12-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movies_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
